"use client";
import axios from "axios";
import React, { useEffect, useState } from "react";

const Navbar = () => {
  const [user, setUser] = useState(''); // State to store user profile
  const token = localStorage.getItem("token");

  // Fetch the user profile when the component mounts
  useEffect(() => {
    if (token) {
      axios
        .get("http://localhost:5000/profile", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        })
        .then((response) => {
          setUser(response.data.user); // Assuming the user data is in response.data.user
        })
        .catch((error) => {
          console.error("Error fetching user profile:", error);
        });
    }
  }, [token]);

  const handleLogout = () => {
    localStorage.removeItem("token");
    setUser(null); // Clear user from state
  };

  return (
    <nav className="flex p-4 shadow-xl rounded border w-full px-4 bg-slate-900">
      <div className="flex w-full justify-between items-center px-5">
        <a
          href="#"
          className="text-slate-200 text-2xl font-extrabold  transition duration-300"
        >
          SocialClipSaver
        </a>

        <div className="lg:hidden">
          <button id="hamburger" className="">
            <svg
              className="w-6 h-6"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              ></path>
            </svg>
          </button>
        </div>

        <ul className="hidden lg:flex space-x-8 items-center">
          <li>
            <a
              href="/youtube"
              className="text-slate-200 transition duration-300"
            >
              YouTube
            </a>
          </li>
          <li>
            <a
              href="instagram"
              className="text-slate-200 transition duration-300"
            >
              Instagram
            </a>
          </li>
          <li>
            <a
              href="facebook"
              className="text-slate-200 transition duration-300"
            >
              Facebook
            </a>
          </li>
          <li>
            <a
              href="video-generated"
              className="text-slate-200 transition duration-300"
            >
              Video Generated by Script
            </a>
          </li>
        </ul>

        <div className="hidden lg:flex space-x-4">
          {user ? (
            <div className="flex items-center">
              <div className="flex flex-col space-y-1">
              <span className="text-slate-200">{user.name}</span>
              <span className="text-slate-200">{user.email}</span>
              </div>
              <button
                onClick={handleLogout}
                className="text-slate-400 border-slate-200 border-2 px-7 py-2 rounded-full transition duration-300"
              >
                Logout
              </button>
            </div>
          ) : (
            <>
              <a
                href="login"
                className="text-slate-400 border-slate-200 border-2 px-7 py-2 rounded-full transition duration-300"
              >
                Login
              </a>
              <a
                href="/signup"
                className="text-slate-400 border-slate-200 border-2 px-7 py-2 rounded-full transition duration-300"
              >
                Sign Up
              </a>
            </>
          )}
        </div>
      </div>

      <div id="mobile-menu" className="lg:hidden hidden">
        <ul className="flex flex-col space-y-4 bg-blue-700 p-4">
          <li>
            <a
              href="Youtube"
              className="text-slate-200 transition duration-300"
            >
              YouTube
            </a>
          </li>
          <li>
            <a
              href="instagram"
              className="text-slate-200 transition duration-300"
            >
              Instagram
            </a>
          </li>
          <li>
            <a
              href="facebook"
              className="text-slate-200 transition duration-300"
            >
              Facebook
            </a>
          </li>
          <li>
            <a
              href="video-generated"
              className="text-slate-200 transition duration-300"
            >
              Video Generated by Script
            </a>
          </li>
          <li>
            {user ? (
              <button
                onClick={handleLogout}
                className="text-slate-200 transition duration-300"
              >
                Logout
              </button>
            ) : (
              <>
                <a
                  href="login"
                  className="hover:bg-green-700 transition duration-300"
                >
                  Login
                </a>
                <a
                  href="signup"
                  className="hover:bg-yellow-700 transition duration-300"
                >
                  Sign Up
                </a>
              </>
            )}
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default Navbar;
